//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVendedores2025.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppVendedores2025.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abierto.
        /// </summary>
        public static string Abierto {
            get {
                return ResourceManager.GetString("Abierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al Carrito.
        /// </summary>
        public static string AgregarCarrito {
            get {
                return ResourceManager.GetString("AgregarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atencion.
        /// </summary>
        public static string Atencion {
            get {
                return ResourceManager.GetString("Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automático.
        /// </summary>
        public static string Automatico {
            get {
                return ResourceManager.GetString("Automatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido!.
        /// </summary>
        public static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permití que &lt;strong&gt;AppVendedores2025 Demo&lt;/strong&gt; use tu ubicación &lt;strong&gt;todo el tiempo&lt;/strong&gt;..
        /// </summary>
        public static string BodyHTML {
            get {
                return ResourceManager.GetString("BodyHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Pedido.
        /// </summary>
        public static string BorrarPedido {
            get {
                return ResourceManager.GetString("BorrarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los pedidos de este cliente se borrarán al transmitir este pedido..
        /// </summary>
        public static string BorrarPedidosAlRestramitir {
            get {
                return ResourceManager.GetString("BorrarPedidosAlRestramitir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Podés cambiar este permiso más adelante desde la configuración del sistema..
        /// </summary>
        public static string Bullet1 {
            get {
                return ResourceManager.GetString("Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usamos tu ubicación sólo para mejorar la trazabilidad de entregas y el mapa de rutas..
        /// </summary>
        public static string Bullet2 {
            get {
                return ResourceManager.GetString("Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bultos.
        /// </summary>
        public static string Bultos {
            get {
                return ResourceManager.GetString("Bultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Por Marca.
        /// </summary>
        public static string BuscarMarcas {
            get {
                return ResourceManager.GetString("BuscarMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cajas de.
        /// </summary>
        public static string Cajas {
            get {
                return ResourceManager.GetString("Cajas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de Combos.
        /// </summary>
        public static string CantidadCombos {
            get {
                return ResourceManager.GetString("CantidadCombos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando.
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito.
        /// </summary>
        public static string Carrito {
            get {
                return ResourceManager.GetString("Carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Carrito no tiene productos ingresados.
        /// </summary>
        public static string CarritoNoIngresados {
            get {
                return ResourceManager.GetString("CarritoNoIngresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalogo.
        /// </summary>
        public static string Catalogo {
            get {
                return ResourceManager.GetString("Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado.
        /// </summary>
        public static string Cerrado {
            get {
                return ResourceManager.GetString("Cerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        public static string Clave {
            get {
                return ResourceManager.GetString("Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combo.
        /// </summary>
        public static string Combo {
            get {
                return ResourceManager.GetString("Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combos.
        /// </summary>
        public static string Combos {
            get {
                return ResourceManager.GetString("Combos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combos y Ofertas.
        /// </summary>
        public static string CombosOfertas {
            get {
                return ResourceManager.GetString("CombosOfertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        public static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con Cargo.
        /// </summary>
        public static string ConCargo {
            get {
                return ResourceManager.GetString("ConCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string Confirmacion {
            get {
                return ResourceManager.GetString("Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas transmitir el pedido?.
        /// </summary>
        public static string ConfirmacionTransmitirPedido {
            get {
                return ResourceManager.GetString("ConfirmacionTransmitirPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Usuario.
        /// </summary>
        public static string CrearUsuario {
            get {
                return ResourceManager.GetString("CrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegar.
        /// </summary>
        public static string Denegar {
            get {
                return ResourceManager.GetString("Denegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Cuenta.
        /// </summary>
        public static string EliminarCuenta {
            get {
                return ResourceManager.GetString("EliminarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta acción iniciará el proceso de eliminación de tu cuenta..
        /// </summary>
        public static string EliminarCuentaDescripcion {
            get {
                return ResourceManager.GetString("EliminarCuentaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Combos.
        /// </summary>
        public static string EnCombos {
            get {
                return ResourceManager.GetString("EnCombos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviado.
        /// </summary>
        public static string Enviado {
            get {
                return ResourceManager.GetString("Enviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar por WhatsApp.
        /// </summary>
        public static string EnviarWhatsapp {
            get {
                return ResourceManager.GetString("EnviarWhatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Arrastres de Combos.
        /// </summary>
        public static string ErrorArrastreCombo {
            get {
                return ResourceManager.GetString("ErrorArrastreCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron encontrar registros de tu pago. ¡Por favor, inténtalo nuevamente!.
        /// </summary>
        public static string ErrorPago {
            get {
                return ResourceManager.GetString("ErrorPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te Falta.
        /// </summary>
        public static string Falta {
            get {
                return ResourceManager.GetString("Falta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forzar sync.
        /// </summary>
        public static string ForzarSync {
            get {
                return ResourceManager.GetString("ForzarSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gps Desactivado.
        /// </summary>
        public static string GpsDesactivado {
            get {
                return ResourceManager.GetString("GpsDesactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar.
        /// </summary>
        public static string Grabar {
            get {
                return ResourceManager.GetString("Grabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gratis.
        /// </summary>
        public static string Gratis {
            get {
                return ResourceManager.GetString("Gratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardo el Combo.
        /// </summary>
        public static string GuardarCombo {
            get {
                return ResourceManager.GetString("GuardarCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion del Pedido.
        /// </summary>
        public static string InformacionPedido {
            get {
                return ResourceManager.GetString("InformacionPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del sistema.
        /// </summary>
        public static string InfoSistema {
            get {
                return ResourceManager.GetString("InfoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos Recientes.
        /// </summary>
        public static string IngresosRecientes {
            get {
                return ResourceManager.GetString("IngresosRecientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listados de Pedidos.
        /// </summary>
        public static string ListadoPedidos {
            get {
                return ResourceManager.GetString("ListadoPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Predeterminada.
        /// </summary>
        public static string ListaPredeterminada {
            get {
                return ResourceManager.GetString("ListaPredeterminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llevar.
        /// </summary>
        public static string Llevar {
            get {
                return ResourceManager.GetString("Llevar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llevas.
        /// </summary>
        public static string Llevas {
            get {
                return ResourceManager.GetString("Llevas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprá rápido o cargá pedidos en segundos.
        /// </summary>
        public static string LoginDivider {
            get {
                return ResourceManager.GetString("LoginDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacé tu pedido en segundos.
        /// </summary>
        public static string LoginSubtitulo {
            get {
                return ResourceManager.GetString("LoginSubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo Mas Pedido.
        /// </summary>
        public static string MasPedido {
            get {
                return ResourceManager.GetString("MasPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor Precio.
        /// </summary>
        public static string MayorPrecio {
            get {
                return ResourceManager.GetString("MayorPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor Venta.
        /// </summary>
        public static string MayorVenta {
            get {
                return ResourceManager.GetString("MayorVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Me Gusta.
        /// </summary>
        public static string MeGusta {
            get {
                return ResourceManager.GetString("MeGusta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor Precio.
        /// </summary>
        public static string MenorPrecio {
            get {
                return ResourceManager.GetString("MenorPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Cuenta.
        /// </summary>
        public static string MiCuenta {
            get {
                return ResourceManager.GetString("MiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El minimo venta es.
        /// </summary>
        public static string MinimoVenta {
            get {
                return ResourceManager.GetString("MinimoVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Pedido.
        /// </summary>
        public static string ModificarPedido {
            get {
                return ResourceManager.GetString("ModificarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevos Ingresos.
        /// </summary>
        public static string NuevosIngresos {
            get {
                return ResourceManager.GetString("NuevosIngresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oferta Combo.
        /// </summary>
        public static string OfertaCombo {
            get {
                return ResourceManager.GetString("OfertaCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu pedido ha ingresado correctamente.
        /// </summary>
        public static string PedidoCorrecto {
            get {
                return ResourceManager.GetString("PedidoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu pedido ha ingresado correctamente..
        /// </summary>
        public static string PedidoIngresado {
            get {
                return ResourceManager.GetString("PedidoIngresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        public static string Pedidos {
            get {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        public static string Pendiente {
            get {
                return ResourceManager.GetString("Pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por el Momento Sin Stock.
        /// </summary>
        public static string PorMomentoSinStock {
            get {
                return ResourceManager.GetString("PorMomentoSinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio&lt;br /&gt;Modificado.
        /// </summary>
        public static string PrecioModificado {
            get {
                return ResourceManager.GetString("PrecioModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precios Modificados.
        /// </summary>
        public static string PreciosModificados {
            get {
                return ResourceManager.GetString("PreciosModificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presentación.
        /// </summary>
        public static string Presentacion {
            get {
                return ResourceManager.GetString("Presentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tuvimos un problema con su pedido. Por favor, comuníquese con AppVendedores2025 Demo. PaymentMP:.
        /// </summary>
        public static string ProblemasPedido {
            get {
                return ResourceManager.GetString("ProblemasPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando....
        /// </summary>
        public static string Procesando {
            get {
                return ResourceManager.GetString("Procesando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProductoDestacado.
        /// </summary>
        public static string ProductoDestacado {
            get {
                return ResourceManager.GetString("ProductoDestacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos Nuevos.
        /// </summary>
        public static string ProductoNuevo {
            get {
                return ResourceManager.GetString("ProductoNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos c/Cargos.
        /// </summary>
        public static string ProductosConCargo {
            get {
                return ResourceManager.GetString("ProductosConCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos Destacados.
        /// </summary>
        public static string ProductosDestacados {
            get {
                return ResourceManager.GetString("ProductosDestacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos Nuevos.
        /// </summary>
        public static string ProductosNuevos {
            get {
                return ResourceManager.GetString("ProductosNuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos s/Cargos.
        /// </summary>
        public static string ProductosSinCargo {
            get {
                return ResourceManager.GetString("ProductosSinCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Querés continuar?.
        /// </summary>
        public static string QuereContinuar {
            get {
                return ResourceManager.GetString("QuereContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reactivar Pedido.
        /// </summary>
        public static string ReactivarPedido {
            get {
                return ResourceManager.GetString("ReactivarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Pago.
        /// </summary>
        public static string RealizarPago {
            get {
                return ResourceManager.GetString("RealizarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Cargo.
        /// </summary>
        public static string SinCargo {
            get {
                return ResourceManager.GetString("SinCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronizacion Completa.
        /// </summary>
        public static string SincronizacionCompleta {
            get {
                return ResourceManager.GetString("SincronizacionCompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronizando....
        /// </summary>
        public static string Sincronizando {
            get {
                return ResourceManager.GetString("Sincronizando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronizar.
        /// </summary>
        public static string Sincronizar {
            get {
                return ResourceManager.GetString("Sincronizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Stock.
        /// </summary>
        public static string SinStock {
            get {
                return ResourceManager.GetString("SinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Alta.
        /// </summary>
        public static string SolicitudAlta {
            get {
                return ResourceManager.GetString("SolicitudAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte.
        /// </summary>
        public static string Soporte {
            get {
                return ResourceManager.GetString("Soporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte técnico.
        /// </summary>
        public static string SoporteTecnico {
            get {
                return ResourceManager.GetString("SoporteTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorá tu cartera y cargá pedidos.
        /// </summary>
        public static string SubClientesTarjeta {
            get {
                return ResourceManager.GetString("SubClientesTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorá el catálogo y cargá tu pedido.
        /// </summary>
        public static string SubIngresarTarjeta {
            get {
                return ResourceManager.GetString("SubIngresarTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisá y gestioná tus pedidos.
        /// </summary>
        public static string SubPedidosTarjeta {
            get {
                return ResourceManager.GetString("SubPedidosTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión de la app.
        /// </summary>
        public static string SubSalirTarjeta {
            get {
                return ResourceManager.GetString("SubSalirTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizá datos y pedidos.
        /// </summary>
        public static string SubSincronizarTarjeta {
            get {
                return ResourceManager.GetString("SubSincronizarTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtené ayuda rápida.
        /// </summary>
        public static string SubSoporteTarjeta {
            get {
                return ResourceManager.GetString("SubSoporteTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AppVendedores2025 Demo recopila datos de ubicación para registrar posición..
        /// </summary>
        public static string SubtextHTML {
            get {
                return ResourceManager.GetString("SubtextHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué necesitás hacer hoy?.
        /// </summary>
        public static string SubtituloBienvenido {
            get {
                return ResourceManager.GetString("SubtituloBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisá tus pedidos anteriores.
        /// </summary>
        public static string SubUltimosPedidosTarjeta {
            get {
                return ResourceManager.GetString("SubUltimosPedidosTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App Vendedores.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar tu ubicación.
        /// </summary>
        public static string TituloUbicacion {
            get {
                return ResourceManager.GetString("TituloUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transmitir.
        /// </summary>
        public static string Transmitir {
            get {
                return ResourceManager.GetString("Transmitir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimas Unidades.
        /// </summary>
        public static string UltimasUnidades {
            get {
                return ResourceManager.GetString("UltimasUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimos Pedidos.
        /// </summary>
        public static string UltimosPedidos {
            get {
                return ResourceManager.GetString("UltimosPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        public static string Unidad {
            get {
                return ResourceManager.GetString("Unidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        public static string Unidades {
            get {
                return ResourceManager.GetString("Unidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaciar.
        /// </summary>
        public static string Vaciar {
            get {
                return ResourceManager.GetString("Vaciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Información del pedido.
        /// </summary>
        public static string VerInformacionPedido {
            get {
                return ResourceManager.GetString("VerInformacionPedido", resourceCulture);
            }
        }
    }
}
